workflows:
  build-run-tests:
    name: Build and run all tests
    instance_type: mac_mini_m1
    environment:
      xcode: 14.2
    triggering:
      events:
        - push
      cancel_previous_builds: false
    working_directory: Hourglass
    max_build_duration: 5
    scripts:
        - name: Show Xcode version
          script: xcode-select -p
        - name: Show Destinations
          script: xcodebuild -project 'Hourglass.xcodeproj' -scheme 'Hourglass' -showdestinations
        - name: Show SDKs
          script: xcodebuild -showsdks
        - name: Build and run all tests on device
          script: >
            xcodebuild clean test
            -project 'Hourglass.xcodeproj'
            -scheme 'HourglassCITesting'
            -destination 'platform=macOS,arch=x86_64'
            -sdk 'macosx13.1'
            -parallel-testing-enabled NO
            | xcpretty && exit ${PIPESTATUS[0]}
