workflows:
  build-and-test:
    name: Build and test
    instance_type: mac_mini_m1
    environment:
      xcode: 14.2
    triggering:
      events:
        - pull_request
        - tag
      cancel_previous_builds: true
    working_directory: Hourglass
    max_build_duration: 4
    scripts:
        - name: Show Xcode version
          script: xcode-select -p
        - name: Show Destinations
          script: xcodebuild -project 'Hourglass.xcodeproj' -scheme 'Hourglass' -showdestinations
        - name: Show SDKs
          script: xcodebuild -showsdks
        - name: Build and test on device
          script: >
            xcodebuild clean test
            -project 'Hourglass.xcodeproj'
            -scheme 'HourglassCITesting'
            -destination 'platform=macOS,arch=x86_64'
            -sdk 'macosx13.1'
            -parallel-testing-enabled NO
            -skip-testing:HourglassUITests/HourglassUITests/testStartTimerToCompletionBanner
            | xcpretty && exit ${PIPESTATUS[0]}
