import CoreData
import Foundation

enum TestData {
    private static func createTimeBlock(start: Date, end: Date, category: TimerCategory) -> TimeBlock {
        let entity = NSEntityDescription.entity(forEntityName: CoreDataEntity.timeBlock.rawValue,
                                                in: CoreDataStore.shared.context)
        let timeBlock = NSManagedObject(entity: entity!, insertInto: nil) as! TimeBlock

        timeBlock.category = Int16(category.rawValue)
        timeBlock.start = start
        timeBlock.end = end

        return timeBlock
    }
    
    static let timeBlocks = [
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 20, minute: 44, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 20, minute: 49, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 20, minute: 07, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 20, minute: 42, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 20, minute: 01, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 20, minute: 06, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 19, minute: 45, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 20, minute: 00, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 19, minute: 32, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 19, minute: 42, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 18, minute: 45, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 19, minute: 30, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 11, minute: 0, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 11, minute: 45, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 10, minute: 47, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 10, minute: 57, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 10, minute: 0, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 26, hour: 10, minute: 45, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 13, minute: 9, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 13, minute: 52, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 13, minute: 02, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 13, minute: 7, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 12, minute: 30, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 13, minute: 00, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 48, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 11, minute: 18, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 40, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 45, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 22, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 37, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 10, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 20, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 9, minute: 43, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 10, minute: 8, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 9, minute: 00, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 24, hour: 9, minute: 40, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 13, minute: 44, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 13, minute: 49, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 13, minute: 24, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 13, minute: 44, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 13, minute: 12, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 13, minute: 22, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 12, minute: 36, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 13, minute: 11, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 12, minute: 00, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 12, minute: 35, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 2, minute: 42, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 2, minute: 57, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 2, minute: 8, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 2, minute: 40, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 1, minute: 58, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 2, minute: 6, second: 58))!,
                        category: .rest),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 1, minute: 24, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 1, minute: 55, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 0, minute: 42, second: 58))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 1, minute: 22, second: 58))!,
                        category: .focus),
        createTimeBlock(start: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 21, hour: 23, minute: 30, second: 0))!,
                        end: Calendar.current.date(from: DateComponents(year: 2023, month: 5, day: 22, hour: 0, minute: 30, second: 0))!,
                        category: .rest),
    ]

    static let timeChunks = [
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 21).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 21).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 21).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 21).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 21).ymdDate, startSeconds: 7000, endSeconds: 7900, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 22).ymdDate, startSeconds: 3000 + 21600, endSeconds: 3900 + 21600, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 22).ymdDate, startSeconds: 5000 + 21600, endSeconds: 6800 + 21600, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 22).ymdDate, startSeconds: 7000 + 21600, endSeconds: 7900 + 21600, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 23).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 23).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 23).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 23).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 23).ymdDate, startSeconds: 7000, endSeconds: 7900, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 24).ymdDate, startSeconds: 3000 + 43200, endSeconds: 3900 + 43200, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 24).ymdDate, startSeconds: 5000 + 43200, endSeconds: 6800 + 43200, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 24).ymdDate, startSeconds: 7000 + 43200, endSeconds: 7900 + 43200, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 25).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 25).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 25).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 25).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 25).ymdDate, startSeconds: 23 * 3600, endSeconds: 24 * 3600, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 26).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 26).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 26).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 26).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 26).ymdDate, startSeconds: 7000, endSeconds: 7900, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 27).ymdDate, startSeconds: 3000 + 21600, endSeconds: 3900 + 21600, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 27).ymdDate, startSeconds: 5000 + 21600, endSeconds: 6800 + 21600, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 27).ymdDate, startSeconds: 7000 + 21600, endSeconds: 7900 + 21600, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 28).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 28).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 28).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 28).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 28).ymdDate, startSeconds: 7000, endSeconds: 7900, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 29).ymdDate, startSeconds: 3000 + 43200, endSeconds: 3900 + 43200, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 29).ymdDate, startSeconds: 5000 + 43200, endSeconds: 6800 + 43200, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 29).ymdDate, startSeconds: 7000 + 43200, endSeconds: 7900 + 43200, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 30).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 30).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 30).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 30).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 5, day: 30).ymdDate, startSeconds: 23 * 3600, endSeconds: 24 * 3600, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 28).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 28).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 28).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 28).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 28).ymdDate, startSeconds: 7000, endSeconds: 7900, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 29).ymdDate, startSeconds: 3000 + 43200, endSeconds: 3900 + 43200, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 29).ymdDate, startSeconds: 5000 + 43200, endSeconds: 6800 + 43200, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 29).ymdDate, startSeconds: 7000 + 43200, endSeconds: 7900 + 43200, category: .focus),

        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 30).ymdDate, startSeconds: 0, endSeconds: 900, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 30).ymdDate, startSeconds: 1000, endSeconds: 2800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 30).ymdDate, startSeconds: 3000, endSeconds: 3900, category: .rest),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 30).ymdDate, startSeconds: 5000, endSeconds: 6800, category: .focus),
        TimeBlock.Chunk(date: DateComponents(year: 2023, month: 6, day: 30).ymdDate, startSeconds: 23 * 3600, endSeconds: 24 * 3600, category: .focus),
    ]
}
